### ISSUE TITLE
Fix i18n

### ISSUE THREAD

**Issue by pmachaux** [Rafarel/angular-i18n-ssr#1]
Va dans `server.ts`
Ligne 53: `server.use('' , appFr);` doit etre absolument apres 
```
    server.use('/fr', appFr);
    server.use('/en', appEn);
```

Donc au final ca doit ressembler a ca:
```
    server.use('/fr', appFr);
    server.use('/en', appEn);
    server.use('' , appFr);
```

L'ordre est important car Express repond au first match. Donc toutes les requetes etaient redirigees vers le `fr`.
De maniere generale pour ce qui est routing, le `default behavior` est toujours en dernier. C'est la meme chose que pour le routing dans l'application Angular elle meme si un jou tu as le cas.

Bon courage pour la suite!

**Comment by Rafarel** [comment]
Merci pour ce retour Pierre, tu as sauvé ma journée !
